import type { Metadata } from "next"
import { Outfit, JetBrains_Mono } from "next/font/google"
import "./globals.css"
import { ThemeProvider } from "@/lib/providers/ThemeProvider"
import AppSidebar from "@/components/common/AppSidebar"
import AppHeader from "@/components/common/AppHeader"
import CusSidebarProvider from "@/lib/providers/CusSidebarProvider"
import { Toaster } from "@/components/ui/sonner"
import { getServerSession } from "@/lib/get-session"

const outfit = Outfit({
  variable: "--font-outfit",
  subsets: ["latin"],
  weight: ["100", "200", "300", "400", "500", "600", "700", "800", "900"],
})

const jetBrains_Mono = JetBrains_Mono({
  variable: "--font-jet-brains-mono",
  subsets: ["latin"],
})

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
}

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  const session = await getServerSession()

  return (
    <html
      lang="en"
      suppressHydrationWarning
    >
      <body
        className={`${outfit.variable} ${jetBrains_Mono.variable} antialiased`}
      >
        <ThemeProvider
          attribute="class"
          defaultTheme="system"
          enableSystem
          disableTransitionOnChange
        >
          <CusSidebarProvider>
            <AppSidebar />
            <main className="w-full min-h-screen bg-card scroll-smooth">
              <AppHeader session={session} />
              <div className="container mx-auto p-2 py-7">{children}</div>
              <Toaster />
            </main>
          </CusSidebarProvider>
        </ThemeProvider>
      </body>
    </html>
  )
}
