import type { Metadata } from "next"
import { Geist, Geist_Mono } from "next/font/google"
import "./globals.css"
import { ThemeProvider } from "@/lib/providers/ThemeProvider"
import AppSidebar from "@/components/common/AppSidebar"
import AppHeader from "@/components/common/AppHeader"
import CusSidebarProvider from "@/lib/providers/CusSidebarProvider"
import AuthProvider from "@/lib/providers/AuthProvider"
import { getServerSession } from "next-auth"
import { authOptions } from "@/lib/auth"

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
})

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
})

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
}

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  const session = await getServerSession(authOptions)
  return (
    <html
      lang="en"
      suppressHydrationWarning
    >
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <AuthProvider session={session!}>
          <ThemeProvider
            attribute="class"
            defaultTheme="system"
            enableSystem
            disableTransitionOnChange
          >
            <CusSidebarProvider>
              <AppSidebar />
              <main className="w-full min-h-screen bg-card scroll-smooth">
                <AppHeader />
                <div className="container mx-auto p-2 py-7">{children}</div>
              </main>
            </CusSidebarProvider>
          </ThemeProvider>
        </AuthProvider>
      </body>
    </html>
  )
}
